export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';

export const CURENT_USER_POSTS_UPDATE = 'CURENT_USER_POSTS_UPDATE';

export const CHATS_SET = 'CHATS_SET';

export const CONNECTS_SET = 'CONNECTS_SET';

export const UPLOADS_SONGS_SET = 'UPLOADS_SONGS_SET';

export const UPLOADS_BEATS_SET = 'UPLOADS_BEATS_SET';

export const MODAL_OPEN_COMMENT_SECTION = 'MODAL_OPEN_COMMENT_SECTION';

export const CLEAR_MODAL = 'CLEAR_MODAL';