export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';

export const CONNECTS_SET = 'CONNECTS_SET';

export const UPLOADS_SONGS_SET = 'UPLOADS_SONGS_SET';

export const UPLOADS_BEATS_SET = 'UPLOADS_BEATS_SET';

export const MODAL_OPEN_COMMENT_SECTION = 'MODAL_OPEN_COMMENT_SECTION';

export const CLEAR_MODAL = 'CLEAR_MODAL';

export const FEED_MODAL_OPEN = 'FEED_MODAL_OPEN';``

export const CLEAR_FEED_OPEN = 'CLEAR_FEED_OPEN';

export const POPUP_1_OPEN = 'POPUP_1_OPEN';

export const POPUP_2_OPEN = 'POPUP_1_OPEN';

export const POPUP_3_OPEN = 'POPUP_1_OPEN';

export const CLEAR_POPUP = 'CLEAR_POPUP';